const List<String> mensagensMotivacional = [
  'Cada dia é uma nova oportunidade para se tornar a melhor versão de si mesmo. Continue firme!',
  'Concentre todas as suas energias nas próximas vinte e quatro horas e vença o dia de hoje.',
  'Não se preocupe com o amanhã, o seu único compromisso com a sobriedade é agora.',
  'Respire fundo e lembre-se de que este momento difícil vai passar se você mantiver o foco.',
  'O dia de hoje é uma página em branco perfeita para você escrever uma história limpa.',
  'Mantenha os seus pés firmes no presente e não deixe a ansiedade guiar os seus passos.',
  'Esqueça os erros do passado e concentre-se no poder que você tem nas mãos hoje.',
  'Se a caminhada parecer difícil, reduza o foco e vença apenas a próxima hora.',
  'Você escolheu a liberdade nas próximas horas e essa é a decisão mais inteligente que existe.',
  'O dia de hoje merece a sua total lucidez e o seu esforço contínuo.',
  'Proteja o seu dia contra qualquer tentação e termine a noite com orgulho de si mesmo.',
  'Cada minuto que você passa sem ceder é uma grande vitória que merece ser celebrada.',
  'Não olhe para o tamanho da montanha, apenas dê o próximo passo com total confiança.',
  'A vontade de recair é passageira, mas o orgulho de resistir vai durar para sempre.',
  'Lembre-se dos seus motivos reais e mantenha o foco total nas escolhas de hoje.',
  'O controle da sua vida está nas suas mãos hoje, faça valer a pena.',
  'Não sabote o seu progresso atual por conta de um impulso momentâneo e passageiro.',
  'Hoje você tem a chance real de fazer escolhas melhores do que fez ontem.',
  'Mantenha a calma e lembre-se de que você é plenamente capaz de vencer o dia de hoje.',
  'A sobriedade de hoje é o alicerce firme para tudo o que você deseja construir.',
  'Concentre-se no que está ao seu alcance agora e deixe o resto se resolver com o tempo.',
  'Nada pode parar uma mente decidida a vencer as próximas vinte e quatro horas com clareza.',
  'Valorize o dia de hoje e não troque a sua paz por uma ilusão momentânea.',
  'Diga não aos velhos hábitos hoje para poder dizer sim a um futuro brilhante amanhã.',
  'O seu compromisso mais importante do dia é manter a sua mente limpa e focada.',
  'Resista ao primeiro impulso com coragem e veja a sua força crescer a cada minuto.',
  'Hoje é o dia perfeito para provar a si mesmo que você recuperou o controle da sua vida.',
  'Sinta o chão sob os seus pés e lembre-se de que o agora é um lugar totalmente seguro.',
  'Não complique o seu caminho, apenas foque em terminar o dia de hoje em sobriedade.',
  'A sua jornada é construída com um passo firme de cada vez, sem pressa.',
  'Silencie os pensamentos negativos e lembre-se do quanto você deseja essa mudança real.',
  'Mais um amanhecer começou e você tem tudo o que precisa para vencer hoje novamente.',
  'Mantenha a guarda alta e proteja a sua sobriedade como o seu bem mais precioso.',
  'Cada escolha consciente que você faz hoje fortalece a sua mente para os próximos dias.',
  'Você é o único responsável por manter o seu dia limpo, confie no seu potencial.',
  'Deixe as preocupações do futuro para depois e viva o dia de hoje com o coração leve.',
  'A sua determinação hoje é o que define o sucesso da sua caminhada rumo à cura.',
  'Não ceda ao cansaço ou ao estresse, a sua sobriedade está acima de qualquer problema.',
  'Hoje você escolheu se amar e se proteger de tudo o que te fazia mal no passado.',
  'Olhe para o espelho agora e prometa que vai lutar por você nas próximas horas.',
  'A urgência do desejo diminui quando você foca a sua atenção em atividades saudáveis.',
  'O dia de hoje guarda conquistas maravilhosas se você mantiver a sua mente totalmente lúcida.',
  'Respeite o seu ritmo atual e não exija demais de si mesmo nas próximas horas.',
  'A sua força de vontade hoje é maior do que qualquer gatilho que possa surgir.',
  'Terminar o dia de hoje limpo é a maior prova de amor-próprio que você pode dar.',
  'Não olhe para trás com arrependimento, use o dia de hoje para fazer tudo diferente.',
  'O momento presente é a sua única realidade, faça dele um espaço de paz e sobriedade.',
  'A sua mente limpa hoje é o melhor presente que você pode oferecer a quem ama você.',
  'Enfrente os desafios das próximas horas com a certeza de que você é forte o suficiente.',
  'Parabéns por escolher a vida e a lucidez em mais um dia de caminhada firme.',
  'Você já provou que é muito mais forte do que qualquer pensamento de desistência.',
  'A dor do crescimento e da mudança é infinitamente menor do que a dor de continuar igual.',
  'Aguente firme a tempestade atual, pois ela está moldando a sua versão mais forte e resiliente.',
  'As suas cicatrizes não mostram fraqueza, elas são a prova viva de que você sobreviveu.',
  'Lembre-se de que você já superou os seus piores dias sem precisar ceder ao vício.',
  'Escolha o desconforto temporário do crescimento em vez da falsa segurança dos velhos erros.',
  'A verdadeira força interior nasce nos momentos em que resistimos quando tudo parece difícil.',
  'O seu passado foi apenas uma lição, ele não define quem você escolheu ser hoje.',
  'O autocontrole diário é a maior e mais bonita liberdade que um ser humano pode conquistar.',
  'Seja sempre muito mais forte do que a sua melhor desculpa para voltar ao passado.',
  'Cair no meio do caminho serve para ajustar o passo; o importante é a sua coragem de levantar.',
  'Você é o verdadeiro mestre do seu destino e tem o poder de escolher caminhos saudáveis.',
  'Nenhuma tempestade emocional dura para sempre, mantenha a calma que o céu vai clarear.',
  'A sua vontade de vencer e mudar de vida deve ser sempre maior do que qualquer tentação.',
  'A sua capacidade de recomeçar do zero prova o tamanho da coragem que existe no seu peito.',
  'Transforme os seus antigos pontos fracos na fortaleza que vai guiar a sua nova vida.',
  'Você redescobriu o poder de dizer não e isso te torna uma pessoa invencível.',
  'A disciplina diária pode parecer difícil no início, mas é ela que vai te libertar de verdade.',
  'Todo o esforço que você faz hoje se transformará no seu maior orgulho no futuro.',
  'Nunca troque o que você mais deseja na vida pelo que você sente vontade agora.',
  'Você é o único autor da sua cura e cada decisão sua escreve um capítulo vitorioso.',
  'A resiliência se tornou a sua nova identidade e nada pode tirar isso de você.',
  'Lembre-se de que o fogo forte é o que molda o aço mais resistente do mundo.',
  'A sua mente é o seu território sagrado, não deixe pensamentos destrutivos entrarem sem permissão.',
  'A verdadeira força não vem da capacidade física, mas de uma vontade que não se dobra.',
  'Você já aprendeu a cair no passado, agora está aprendendo a lutar e vencer.',
  'Nunca subestime a sua impressionante capacidade de superação diante dos momentos de crise.',
  'Mantenha a promessa de sobriedade que você fez para si mesmo e não quebre esse pacto.',
  'Você se tornou o guarda oficial do seu próprio bem-estar e da sua estabilidade mental.',
  'A fraqueza de um momento é passageira, mas o orgulho de continuar limpo é permanente.',
  'Resista ao primeiro impulso com toda a sua energia e veja o desejo desaparecer aos poucos.',
  'Lembre-se de que você já superou barreiras muito maiores do que essa que está na sua frente.',
  'Escolher a sobriedade todos os dias é um ato de bravura extrema que poucos conseguem.',
  'Seja o escudo definitivo contra os seus velhos hábitos e proteja a sua nova rotina.',
  'O poder absoluto de escolha é totalmente seu e ninguém pode tirar essa autonomia de você.',
  'Mantenha-se firme como uma rocha diante de qualquer desejo ou gatilho emocional.',
  'Você passou por coisas difíceis demais para quebrar por causa de um momento de fraqueza.',
  'Olhe para trás apenas para contemplar com orgulho o longo caminho que você já percorreu.',
  'A tempestade atual serve para limpar o ar e te mostrar o quanto você consegue aguentar.',
  'Domine os seus impulsos mais profundos antes que eles tentem dominar a sua vida novamente.',
  'Cada "não" que você diz para o vício fortalece a sua alma e a sua determinação.',
  'Você escolheu o caminho mais difícil porque sabe que ele é o único que traz paz real.',
  'A dor do crescimento pessoal sempre traz uma sensação de paz inexplicável no final do dia.',
  'Seja totalmente implacável com as suas metas de saúde e não aceite menos do que o sucesso.',
  'Você assumiu o papel de capitão da sua própria mente e agora dita as regras do jogo.',
  'O desconforto que você sente é o sinal claro de que a sua vida está mudando para melhor.',
  'Não ceda de forma alguma àquilo que passou anos destruindo a sua felicidade e saúde.',
  'A sua resiliência diária serve de inspiração para todas as pessoas que estão ao seu redor.',
  'Você descobriu que é infinitamente maior e mais forte do que qualquer vício ou dependência.',
  'A sua força real não está no destino final, mas na coragem de dar o próximo passo.',
  'Você merece viver uma vida limpa, leve e cheia de momentos verdadeiramente felizes.',
  'Seja profundamente gentil com o seu processo de cura e respeite o tempo do seu corpo.',
  'Você é uma pessoa digna de paz, amor e de um futuro livre de correntes.',
  'Perdoe o seu passado de uma vez por todas, você estava apenas tentando sobreviver.',
  'O seu valor real como ser humano não é definido pelos erros que você cometeu.',
  'Você está construindo dia após dia uma pessoa de quem vai sentir muito orgulho.',
  'Cuide de si mesmo com a paciência e o carinho que você dedicaria a um melhor amigo.',
  'Lembre-se sempre de que você é o projeto de vida mais importante que possui.',
  'Aprenda a amar e valorizar a pessoa incrível que você está se tornando neste processo.',
  'A sua história de superação tem um valor inestimável e pode ajudar outras pessoas.',
  'Celebre cada pequena vitória diária, pois são elas que constroem o seu grande sucesso.',
  'Você é perfeitamente suficiente hoje e não precisa provar nada para ninguém além de si.',
  'Escolher a sobriedade é o maior e mais bonito ato de amor-próprio que você pode praticar.',
  'Trate a sua mente e o seu corpo com a bondade e o respeito que você realmente merece.',
  'Entenda que você é uma obra de arte em constante construção e evolução diária.',
  'O respeito próprio deve ser sempre um valor inegociável na sua nova rotina de vida.',
  'Você merece colher o melhor que a vida tem a oferecer através da sua lucidez.',
  'Orgulhe-se imensamente de não ter desistido nos dias em que tudo parecia desabar.',
  'A sua saúde mental e o seu equilíbrio emocional devem ser as suas prioridades máximas.',
  'Você é muito mais do que uma simples contagem de dias; você é uma história de sucesso.',
  'Permita-se sentir alegria verdadeira nas pequenas coisas da sua nova rotina saudável.',
  'A cura emocional não acontece em linha reta, aceite os dias difíceis como parte do aprendizado.',
  'Você é uma pessoa preciosa demais para continuar se destruindo com velhos hábitos ruins.',
  'Olhe no espelho com a cabeça erguida e sinta orgulho da sua postura corajosa hoje.',
  'A sua jornada de recuperação é única, bela e cheia de significados profundos.',
  'Vista a sua sobriedade como uma verdadeira medalha de honra conquistada com esforço.',
  'Você está resgatando a sua essência mais pura e verdadeira que estava adormecida.',
  'Acolha as suas vulnerabilidades com carinho para poder transformá-las em pura força.',
  'Você tem todo o direito de deitar a cabeça no travesseiro e dormir em paz todas as noites.',
  'O amor-próprio reconstrói com paciência tudo aquilo que o vício acabou quebrando no passado.',
  'Valorize o effort interno silencioso que você faz e que muitas vezes ninguém consegue ver.',
  'Você assumiu o papel de maior protetor da sua própria felicidade e estabilidade.',
  'A sua vida tem um propósito lindo e a lucidez é o caminho para descobri-lo por completo.',
  'Não se compare com o progresso dos outros; compare-se apenas com quem você era ontem.',
  'Você finalmente conquistou a liberdade necessária para ser quem você realmente deseja ser.',
  'O seu auto-respeito cresce e se fortalece a cada novo dia que você passa totalmente limpo.',
  'Seja sempre o seu maior aliado e o seu melhor incentivador nessa longa caminhada.',
  'Você merece viver a vida em sua plenitude total, e não apenas existir nas sombras.',
  'Manter a sua mente limpa e clara é o maior tesouro que você poderia conquistar.',
  'Lembre-se de agradecer a si mesmo antes de dormir pela escolha corajosa feita hoje.',
  'O seu valor como pessoa é real, imutável e não depende da opinião de terceiros.',
  'Proteja o seu coração e a sua rotina de qualquer influência externa que te puxe para baixo.',
  'Você demonstra uma força gigante ao aceitar sentir todas as emoções da vida sem anestesia.',
  'A caminhada da sobriedade te devolveu a dignidade e o respeito que haviam sumido.',
  'Sorria e comemore cada centímetro de progresso que você conquistou com o seu suor.',
  'Pare de procurar fora; você descobriu que a cura que tanto precisava estava dentro de si.',
  'O seu corpo é o seu templo mais sagrado, cuide dele com a melhor alimentação e hábitos.',
  'A paz interior que você sente agora é o seu novo lar estável e seguro.',
  'Você tem todo o direito do mundo de sentir um orgulho profundo da sua transformação.',
  'No momento em que você escolheu a si mesmo, o mundo inteiro mudou ao seu redor.',
  'O melhor momento da sua vida ainda está por vir e será construído com a sua lucidez.',
  'Use a sua energia de hoje para projetar o futuro livre e feliz que você sempre sonhou.',
  'A clareza mental que você conquistou abre portas que antes pareciam trancadas para sempre.',
  'Todos os seus sonhos mais ousados se tornam possíveis quando você mantém a sua sobriedade.',
  'A verdadeira liberdade te dá asas para voar em direção a objetivos muito mais altos.',
  'O seu futuro agora é um campo aberto de infinitas oportunidades e escolhas saudáveis.',
  'Você está criando um legado inestimável de superação para as futuras gerações da sua família.',
  'Uma vida completamente nova e cheia de significado está sendo desenhada por você agora.',
  'Redescubra as cores e as belezas do mundo através de olhos totalmente limpos e atentos.',
  'Os seus objetivos de vida estão visivelmente mais perto de serem alcançados no dia de hoje.',
  'A sobriedade contínua é a chave mestra para destravar o seu verdadeiro potencial oculto.',
  'Viva com intensidade a reality que você sempre quis e que agora bate à sua porta.',
  'Você recuperou as rédeas do seu destino e agora escolhe para onde quer seguir.',
  'Novas estradas e objetivos grandiosos exigem a manutenção constante dos seus novos hábitos.',
  'Tudo o que você planta com esforço hoje será colhido com muita alegria e paz amanhã.',
  'A clareza de pensamento traz o discernimento necessário para aproveitar as grandes chances.',
  'Seja hoje a grande inspiração de superação que você tanto precisava encontrar no seu passado.',
  'Os seus horizontes pessoais se expandiram de uma forma que você nunca achou possível.',
  'O mundo se torna um lugar muito maior e mais interessante quando estamos totalmente lúcidos.',
  'Crie conexões humanas verdadeiras e profundas baseadas na sua nova versão transparente.',
  'A sua nova vida livre de amarras não possui limites para o crescimento pessoal.',
  'Invista no sucesso do seu amanhã mantendo a firmeza e o foco no dia de hoje.',
  'A sobriedade diária revela as qualidades e talentos reais que o vício tentou esconder.',
  'O caminho que se estende à sua frente é brilhante e cheio de realizações fantásticas.',
  'Você quebrou definitivamente as correntes pesadas que te amarravam aos erros do passado.',
  'Viva cada momento com um propósito claro na mente e uma direção bem definida no coração.',
  'A vida lúcida mostra que a realidade pode ser maravilhosa sem a necessidade de fugas.',
  'Você assumiu o banco do motorista da sua existência e agora pilota rumo ao sucesso.',
  'Desperte todas as manhãs entusiasmado com as infinitas possibilidades que o dia oferece.',
  'O seu potencial máximo como ser humano está esperando para ser explorado por você.',
  'A sobriedade reconstrói pontes sólidas com as pessoas que realmente importam na sua vida.',
  'O seu eu do futuro vai agradecer profundamente pela escolha corajosa que você faz hoje.',
  'Sinta o leveza de ser livre para voar mais alto e alcançar os seus maiores objetivos.',
  'O seu foco inabalável na saúde atrai naturalmente o sucesso em todas as outras áreas.',
  'A sua transformação pessoal é um processo completo, contínuo e maravilhoso de se ver.',
  'Você está escrevendo de próprio punho uma das histórias de vitória mais lindas já vistas.',
  'O futuro não assusta quem aprendeu a dominar os seus impulsos no momento presente.',
  'Novas paixões, hobbys e talentos esperam para ser descobertos pela sua mente limpa.',
  'A escolha de viver em sobriedade abre portas invisíveis de evolução espiritual e mental.',
  'Você tem um mundo inteiro cheio de novidades para explorar com a sua nova consciência.',
  'Mantenha os seus olhos fixos na maior recompensa de todas: a sua paz de espírito.',
  'A sua evolução como pessoa é visível, real e inspira admiração em todos nós.',
  'O amanhã reserva momentos de profunda paz e conquistas que você nem consegue imaginar.',
  'Você recuperou o seu tempo de vida útil e agora cada segundo pertence estritamente a você.',
  'Caminhe de cabeça erguida e sinta um orgulho legítimo de cada passo dessa trajetória.',
  'O seu propósito de vida atual é infinitamente maior do que qualquer distração momentânea.',
  'A lucidez constante se tornou o seu superpoder mais forte para enfrentar qualquer crise.',
  'Caminhe com passos firmes e decididos na direção dos sonhos que você deixou para trás.',
  'A vida recupera a sua verdadeira beleza quando temos a coragem de encará-la de frente.',
  'Você venceu os desafios de ontem, está dominando o dia de hoje e colherá a vitória sempre.',
];
